name: Deploy - Dev

on:
  push:
    branches: [ "master" ]
    paths:
      - "template.yaml"
      - "stacks/**"
      - "functions/**"
      - ".github/workflows/**"

concurrency:
  group: sam-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  STACK_NAME: insider-case-health-dev
  ENV_NAME: dev
  SUFFIX: ""
  SERVICE_TAG: insider-case

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          role-session-name: ci-dev-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build
        run: |
          set -euo pipefail
          sam build --template-file template.yaml

      - name: Deploy
        run: |
          set -euo pipefail
          sam deploy \
            --template-file template.yaml \
            --stack-name "${STACK_NAME}" \
            --capabilities CAPABILITY_IAM \
            --region "${AWS_REGION}" \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              AppName=insider-case \
              EnvName=${ENV_NAME} \
              Suffix=${SUFFIX} \
              ReleaseVersion=${GITHUB_SHA} \
              EnvTag=${ENV_NAME} \
              ServiceTag=${SERVICE_TAG}
